package enums;

public enum ConfigurationProperties {
	RUN_ON, SERVER_IP, PORT, DEVICE_NAME, PLATFORM_NAME, PLATFORM_VERSION, APP_PATH, APP_PACKAGE, APP_ACTIVITY, BASE_URL, BROWSER_NAME, CHROME_DRIVER_PATH, FIREFOX_DRIVER_PATH, 
	REPORT_CONFIG_PATH, REPORT_PATH, LAST_RUN, REPORT_TEMPLATE,
	TO, FROM, CC, SUBJECT
}
